### ISSUE TITLE
Update generated projects with new template

### ISSUE THREAD

**Issue by mathieudutour** [mathieudutour/medium-to-own-blog#30]
Need to figure out a way for generated projects to pull changes that are happening in the template.

Not sure how tho :thinking:

**Comment by dbarochiya** [comment]
We can upload all the medium archives to the GitHub itself {only necessary things} when the user creates the repository first time. We also need to save the time of the first build so that the changes made by the user can be differentiated from the initial import

We can have an update-script (Also can be served as NPM module) which does the following things,
* parse the archival to create articles in the .md format  
* update the articles which are not changed by the user after the initial import 
* commit & update the changes

I am not sure how to re-create the profile/code changes made by the user afterward (like I have added some social media links)

**Comment by mathieudutour** [comment]
I was more thinking about a npm script which apply the content of `gatsby-template/src` to the current folder.

That way you can still see the diffs with git, etc.. 

I don't think we want to regenerate the articles, it's mostly just for the source of the gatsby project

**Comment by jletey** [comment]
@mathieudutour Why don’t we just have a Gatsby theme that allows component shadowing ... then whenever we make a change to the theme, we just publish a new version and then the user can just choose whether or not to update

**Comment by mathieudutour** [comment]
@johnletey that's another possibility yes, I haven't really looked at themes yet. Would you like to try it and send a PR?

**Comment by jletey** [comment]
Would be happy too ... if you don’t mind, I’ll probably set up yarn workspaces

**Comment by mathieudutour** [comment]
Err could we just have the theme in a `gatsby-theme` folder? No need to use lerna or yarn which add a barrier to entry to new contributors IMO

**Comment by jletey** [comment]
I’m pretty sure ... I’ll keep you posted!

**Comment by jletey** [comment]
Another nice thing about using a theme is that people who personally like the theme, but don’t have any medium posts to import can still use the theme!

**Comment by mathieudutour** [comment]
that's very true :+1:

**Comment by dbarochiya** [comment]
>I don't think we want to regenerate the articles, it's mostly just for the source of the gatsby project

The reason I proposed this was that if we fix some bugs in the parsing mechanism then it would not be able to regenerate articles with the new version. But I guess almost all bugs are fixed now !! 

Making Independent template is a really good idea, looking forward to it !!

**Comment by jletey** [comment]
@mathieudutour @dbarochiya So sorry guys ... I've been busy lately ... I will hopefully have a PR up for this by mid-week!

**Comment by mathieudutour** [comment]
Fixed in the new version
