### ISSUE TITLE
Why people want to export medium blogs?

### ISSUE THREAD

**Issue by lk1ngaa7** [mathieudutour/medium-to-own-blog#38]

**Comment by mathieudutour** [comment]
A few reasons:
- Medium started to add signin full screen popup everywhere
- Medium doesn't really recommend your articles anymore if you don't put them behind their paywall
- If/When Medium disappears, you will have lost all your "brand"

So it'd better to write the articles on your own blog and then import them to Medium so that Medium links back to your blog
